import dns from "dns";
import fs from "fs";
import { urls } from "./constants.js";

const retry = async (fn, n) => {
  for (let i = 0; i < n; i++) {
    try {
      return await fn();
    } catch {}
  }
  return {
    failed: true,
  };
};

const getHostConfig = async (url) => {
  const getConfig = async () => {
    const response = await dns.promises.lookup(url);
    return { url, ip: response.address };
  };
  try {
    const config = await retry(getConfig, 3);
    if (config.failed) {
      return { url, ip: "" };
    }
    return config;
  } catch {}
};

const resolveUrls = async () => {
  const promises = urls.map(getHostConfig);
  return Promise.all(promises);
};

const generateHosts = (configs) => {
  let hostStr = "# Generated by hosts-generator\n\n";
  configs.forEach((i) => {
    const whiteLen = 16 - i.ip.length;
    if (!i.ip) {
      hostStr += `# ${i.url} update failed\n`;
    } else {
      hostStr += `${i.ip} ${" ".repeat(whiteLen)} ${i.url}\n`;
    }
  });
  hostStr += "\n# Generated by hosts-generator";
  return hostStr;
};

const writeHosts = (hosts) => {
  const str = generateHosts(hosts);
  fs.writeFileSync("./hosts", str);
};

const main = async () => {
  const configs = await resolveUrls();
  writeHosts(configs);
};

main();
