import fs from "fs/promises";
import { type HostConfig } from "./dns.js";
import { TEMPLATE_PATH, OUTPUT_PATHS } from "./constants.js";

const HEADER = "# Generated by Github Hosts start \n\n";
const FOOTER = "# Generated by Github Hosts end";
const REPO_URL = "https://github.com/fliu2476/gh-hosts.git";

export const generateHostsContent = (configs: HostConfig[]): string => {
  let content = HEADER;

  configs.forEach(({ url, ip }) => {
    if (!ip) {
      content += `# ${url} update failed\n`;
    } else {
      // Align IPs for better readability (max IP length is 15 for IPv4)
      const padding = " ".repeat(Math.max(1, 16 - ip.length));
      content += `${ip}${padding}${url}\n`;
    }
  });

  const updateTime = new Date().toLocaleString("en-US", {
    timeZone: "Asia/Shanghai",
  });

  content += `\n# Last update: ${updateTime}\n`;
  content += `# Please star: ${REPO_URL}\n`;
  content += FOOTER;

  return content;
};

export const updateFiles = async (configs: HostConfig[]) => {
  const hostsContent = generateHostsContent(configs);
  const updateTime = new Date().toLocaleString("en-US", {
    timeZone: "Asia/Shanghai",
  });

  try {
    // Read template
    const template = await fs.readFile(TEMPLATE_PATH, "utf-8");
    
    // Replace placeholders
    const readmeContent = template
      .replace("{{hosts}}", hostsContent)
      .replace("{{last_update_time}}", updateTime);

    // Write files concurrently
    await Promise.all([
      fs.writeFile(OUTPUT_PATHS.HOSTS, hostsContent),
      fs.writeFile(OUTPUT_PATHS.README, readmeContent),
      fs.writeFile(OUTPUT_PATHS.README_CN, readmeContent),
    ]);

    console.log(`[Success] Updated hosts and READMEs at ${updateTime}`);
  } catch (error) {
    console.error("[Error] Failed to update files:", error);
    process.exit(1);
  }
};
